### ISSUE TITLE
Design user stories

### ISSUE THREAD

**Issue by cbretn** [cbretn/jollypops#3]
### To-Do

- [ ] design mandatory user stories
- [ ] design optional user stories
- [ ] ask for LWT review
- [ ] merge comments
- [ ] validate final version

### Notes

Design user stories

As a guest user, I can login as a renter

As a guest user, I can login as a rentee

As a renter,
I can add my pop-up space to a listing

As a rentee,
I can search for a pop-up space by location

As a rentee,
I can see when the pop-up space is available

As a rentee,
I can book a pop-up space 

As a renter,
I’m notified when someone books my space

As a renter,
I can have a calendar of when my space is being rented

As a renter and rentee, I can message the other party to figure out the details

As a rentee, I can leave a review for a pop-up space, after my stay

OPTIONAL:

As a rentee, I can search for a pop-up space by tag

As a renter, I can add a description with amenities, tags… to my pop-up space listing

As a rentee, I can pay for a pop-up space rental

As a renter, I can receive payment

As a renter, I can accept or decline a booking proposition

As a rentee, I can cancel a booking
