### ISSUE TITLE
Create Rails app

### ISSUE THREAD

**Issue by cbretn** [cbretn/jollypops#5]
### To-Do

- [x] initiate new rails project (with postgreSQL db and devise gem + LW ui boilerplate config)
- [x] create github repository
- [x] push new rails app to github
- [x] add collborators
- [x] create heroku app
- [x] save heroku app url in repository description
