### ISSUE TITLE
Jollypops Logo & Text Logo

### ISSUE THREAD

**Issue by cbretn** [cbretn/jollypops#7]
### To-Do

- [x] Design Logo
- [x] Design text logo
- [x] get review comments
- [x] merge review
- [x] validate final versions

### Information for review:

Logo and text logo are in figma components
