### ISSUE TITLE
Figma Mockups

### ISSUE THREAD

**Issue by cbretn** [cbretn/jollypops#8]
### To-Do

- [x] Components: buttons, card, maps, navbar, fonts, logo, images...
- [x] Home Page
- [x] Spaces listings page
- [x] Log-in Form
- [x] Booking Page
- [x] Message Page
- [x] Payment Page
- [x] Profile Page

**Comment by LorenzoXavier** [comment]
Mock ups completed - url is 
https://www.figma.com/file/ENAb53LDAQlY0VgTqPqzZvM3/JollyPops?node-id=1%3A3
Went through mock ups as a team and agreed on basic format, styling and user flow.

**Comment by cbretn** [comment]
looks good!
